;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-pair-delete-pair
        kill-region
        rjsx-delete-creates-full-tag
        ))

(setq mc/cmds-to-run-once
      '(
        magit-status
        ))
